### ISSUE TITLE
Add note about `ActiveSupport::Configurable requirement ("undefined method `configure' for [YourAppName]:Module" error)

### ISSUE THREAD

**Issue by xunker** [freeletics/creds#7] opened 2019-01-22 17:32 UTC
I found that this gem requires `ActiveSupport::Configurable` to be added to your `application.rb`, it may be worth adding a note about that to the Readme. This module may be included by default new Rails apps, but I am working with app that began with Rails 2.x and has been upgraded to Rails 5.2 and did not have it.

For any one who has had the error:
> undefined method `configure' for [YourAppName]:Module

You will need to add `include ActiveSupport::Configurable` to your `application.rb` here:

```ruby
# ...
module YourAppName # this will be the name of your app
  include ActiveSupport::Configurable # this is the line to add

  class Application < Rails::Application
# ...
```

**Comment by morgoth** [comment] 2019-04-17 18:29
Looks like some issue during upgrade?
In Rails 5.2 apps there is no need for such addition

**Comment by morgoth** [comment] 2019-05-28 14:46
@xunker if you can push some sample app that shows the problem, please do. I'll close it for now as I cannot reproduce

**Closed as completed by morgoth** 2019-05-28 14:46 UTC
